const WORDS = [
    { spanish: "ser", english: "to be" },
    { spanish: "estar", english: "to be (temporary)" },
    { spanish: "tener", english: "to have" },
    { spanish: "hacer", english: "to do" },
    { spanish: "decir", english: "to say" },
    { spanish: "ir", english: "to go" },
    { spanish: "ver", english: "to see" },
    { spanish: "dar", english: "to give" },
    { spanish: "saber", english: "to know" },
    { spanish: "querer", english: "to want" },
    { spanish: "llegar", english: "to arrive" },
    { spanish: "pasar", english: "to happen" },
    { spanish: "deber", english: "must" },
    { spanish: "poner", english: "to put" },
    { spanish: "parecer", english: "to seem" },
    { spanish: "quedar", english: "to stay" },
    { spanish: "creer", english: "to believe" },
    { spanish: "hablar", english: "to speak" },
    { spanish: "llevar", english: "to carry" },
    { spanish: "dejar", english: "to leave" },
    { spanish: "seguir", english: "to follow" },
    { spanish: "encontrar", english: "to find" },
    { spanish: "llamar", english: "to call" },
    { spanish: "venir", english: "to come" },
    { spanish: "pensar", english: "to think" },
    { spanish: "salir", english: "to leave" },
    { spanish: "volver", english: "to return" },
    { spanish: "tomar", english: "to take" },
    { spanish: "conocer", english: "to know (people)" },
    { spanish: "vivir", english: "to live" },
    { spanish: "sentir", english: "to feel" },
    { spanish: "tratar", english: "to try" },
    { spanish: "mirar", english: "to look" },
    { spanish: "contar", english: "to tell" },
    { spanish: "empezar", english: "to begin" },
    
    { spanish: "casa", english: "house" },
    { spanish: "tiempo", english: "time" },
    { spanish: "vida", english: "life" },
    { spanish: "dia", english: "day" },
    { spanish: "ano", english: "year" },
    { spanish: "mano", english: "hand" },
    { spanish: "parte", english: "part" },
    { spanish: "lugar", english: "place" },
    { spanish: "caso", english: "case" },
    { spanish: "trabajo", english: "work" },
    { spanish: "gente", english: "people" },
    { spanish: "forma", english: "form" },
    { spanish: "mundo", english: "world" },
    { spanish: "niño", english: "child" },
    { spanish: "hombre", english: "man" },
    { spanish: "mujer", english: "woman" },
    { spanish: "amigo", english: "friend" },
    { spanish: "agua", english: "water" },
    { spanish: "comida", english: "food" },
    { spanish: "libro", english: "book" },
    { spanish: "ciudad", english: "city" },
    { spanish: "familia", english: "family" },
    { spanish: "historia", english: "history" },
    { spanish: "ejemplo", english: "example" },
    
    { spanish: "perro", english: "dog" },
    { spanish: "gato", english: "cat" },
    { spanish: "pajaro", english: "bird" },
    { spanish: "pez", english: "fish" },
    { spanish: "coche", english: "car" },
    { spanish: "tren", english: "train" },
    { spanish: "calle", english: "street" },
    { spanish: "escuela", english: "school" },
    { spanish: "maestro", english: "teacher" },
    { spanish: "estudiante", english: "student" },
    { spanish: "dinero", english: "money" },
    { spanish: "tienda", english: "store" },
    { spanish: "puerta", english: "door" },
    { spanish: "ventana", english: "window" },
    { spanish: "mesa", english: "table" },
    { spanish: "silla", english: "chair" },
    { spanish: "cama", english: "bed" },
    { spanish: "cocina", english: "kitchen" },
    { spanish: "baño", english: "bathroom" },
    
    { spanish: "comer", english: "to eat" },
    { spanish: "beber", english: "to drink" },
    { spanish: "abrir", english: "to open" },
    { spanish: "cerrar", english: "to close" },
    { spanish: "leer", english: "to read" },
    { spanish: "escribir", english: "to write" },
    { spanish: "comprar", english: "to buy" },
    { spanish: "vender", english: "to sell" },
    { spanish: "pagar", english: "to pay" },
    { spanish: "trabajar", english: "to work" },
    { spanish: "jugar", english: "to play" },
    { spanish: "correr", english: "to run" },
    { spanish: "caminar", english: "to walk" },
    { spanish: "dormir", english: "to sleep" },
    { spanish: "subir", english: "to go up" },
    { spanish: "bajar", english: "to go down" },
    { spanish: "entrar", english: "to enter" },
    { spanish: "recordar", english: "to remember" },
    { spanish: "olvidar", english: "to forget" },
    { spanish: "amar", english: "to love" },
    { spanish: "odiar", english: "to hate" },
    { spanish: "necesitar", english: "to need" },
    { spanish: "usar", english: "to use" },
    { spanish: "intentar", english: "to try" },
    { spanish: "ayudar", english: "to help" },
    { spanish: "cambiar", english: "to change" },
    { spanish: "terminar", english: "to finish" },
    
    { spanish: "bueno", english: "good" },
    { spanish: "malo", english: "bad" },
    { spanish: "grande", english: "big" },
    { spanish: "pequeño", english: "small" },
    { spanish: "nuevo", english: "new" },
    { spanish: "viejo", english: "old" },
    { spanish: "alto", english: "tall" },
    { spanish: "bajo", english: "short" },
    { spanish: "mejor", english: "better" },
    { spanish: "peor", english: "worse" },
    
    { spanish: "si", english: "yes" },
    { spanish: "no", english: "no" },
    { spanish: "muy", english: "very" },
    { spanish: "tambien", english: "also" },
    { spanish: "solo", english: "only" },
    { spanish: "aqui", english: "here" },
    { spanish: "alli", english: "there" },
    { spanish: "entonces", english: "then" },
    { spanish: "porque", english: "because" },
    { spanish: "aunque", english: "although" },
{ spanish: "mientras", english: "while" },
{ spanish: "antes", english: "before" },
{ spanish: "despues", english: "after" },
{ spanish: "siempre", english: "always" },
{ spanish: "nunca", english: "never" },
{ spanish: "a veces", english: "sometimes" },
{ spanish: "casi", english: "almost" },
{ spanish: "todavia", english: "still" },
{ spanish: "ya", english: "already" },

// MORE VERBS
{ spanish: "aprender", english: "to learn" },
{ spanish: "enseñar", english: "to teach" },
{ spanish: "viajar", english: "to travel" },
{ spanish: "visitar", english: "to visit" },
{ spanish: "quedarse", english: "to stay" },
{ spanish: "entrar", english: "to enter" },
{ spanish: "saludar", english: "to greet" },
{ spanish: "escuchar", english: "to listen" },
{ spanish: "oir", english: "to hear" },
{ spanish: "mirar", english: "to watch" },
{ spanish: "ver", english: "to see" },
{ spanish: "tocar", english: "to touch" },
{ spanish: "sentarse", english: "to sit" },
{ spanish: "levantarse", english: "to stand" },
{ spanish: "abrir", english: "to open" },
{ spanish: "cerrar", english: "to close" },
{ spanish: "romper", english: "to break" },
{ spanish: "arreglar", english: "to fix" },
{ spanish: "crear", english: "to create" },
{ spanish: "construir", english: "to build" },
{ spanish: "empezar", english: "to start" },
{ spanish: "continuar", english: "to continue" },
{ spanish: "parar", english: "to stop" },
{ spanish: "intentar", english: "to attempt" },
{ spanish: "lograr", english: "to achieve" },
{ spanish: "ganar", english: "to win" },
{ spanish: "perder", english: "to lose" },
{ spanish: "abrir", english: "to open" },
{ spanish: "cerrar", english: "to close" },
{ spanish: "caer", english: "to fall" },
{ spanish: "levantar", english: "to lift" },
{ spanish: "tirar", english: "to throw" },
{ spanish: "recibir", english: "to receive" },
{ spanish: "enviar", english: "to send" },
{ spanish: "mostrar", english: "to show" },
{ spanish: "explicar", english: "to explain" },
{ spanish: "preguntar", english: "to ask" },
{ spanish: "responder", english: "to answer" },

// DAILY NOUNS
{ spanish: "pan", english: "bread" },
{ spanish: "leche", english: "milk" },
{ spanish: "queso", english: "cheese" },
{ spanish: "huevo", english: "egg" },
{ spanish: "carne", english: "meat" },
{ spanish: "fruta", english: "fruit" },
{ spanish: "verdura", english: "vegetable" },
{ spanish: "arroz", english: "rice" },
{ spanish: "pasta", english: "pasta" },
{ spanish: "azucar", english: "sugar" },
{ spanish: "sal", english: "salt" },
{ spanish: "cafe", english: "coffee" },
{ spanish: "te", english: "tea" },
{ spanish: "jugo", english: "juice" },

{ spanish: "hospital", english: "hospital" },
{ spanish: "doctor", english: "doctor" },
{ spanish: "enfermera", english: "nurse" },
{ spanish: "medicina", english: "medicine" },
{ spanish: "dolor", english: "pain" },
{ spanish: "salud", english: "health" },

{ spanish: "oficina", english: "office" },
{ spanish: "empresa", english: "company" },
{ spanish: "jefe", english: "boss" },
{ spanish: "empleado", english: "employee" },
{ spanish: "reunion", english: "meeting" },

{ spanish: "telefono", english: "phone" },
{ spanish: "computadora", english: "computer" },
{ spanish: "internet", english: "internet" },
{ spanish: "pantalla", english: "screen" },
{ spanish: "teclado", english: "keyboard" },

// ADJECTIVES
{ spanish: "feliz", english: "happy" },
{ spanish: "triste", english: "sad" },
{ spanish: "rapido", english: "fast" },
{ spanish: "lento", english: "slow" },
{ spanish: "facil", english: "easy" },
{ spanish: "dificil", english: "difficult" },
{ spanish: "fuerte", english: "strong" },
{ spanish: "debil", english: "weak" },
{ spanish: "rico", english: "rich" },
{ spanish: "pobre", english: "poor" },
{ spanish: "lleno", english: "full" },
{ spanish: "vacio", english: "empty" },
{ spanish: "limpio", english: "clean" },
{ spanish: "sucio", english: "dirty" },
{ spanish: "caliente", english: "hot" },
{ spanish: "frio", english: "cold" },
{ spanish: "duro", english: "hard" },
{ spanish: "suave", english: "soft" },
{ spanish: "seguro", english: "safe" },
{ spanish: "peligroso", english: "dangerous" },

// NUMBERS
{ spanish: "uno", english: "one" },
{ spanish: "dos", english: "two" },
{ spanish: "tres", english: "three" },
{ spanish: "cuatro", english: "four" },
{ spanish: "cinco", english: "five" },
{ spanish: "seis", english: "six" },
{ spanish: "siete", english: "seven" },
{ spanish: "ocho", english: "eight" },
{ spanish: "nueve", english: "nine" },
{ spanish: "diez", english: "ten" },

// PLACES
{ spanish: "parque", english: "park" },
{ spanish: "playa", english: "beach" },
{ spanish: "montaña", english: "mountain" },
{ spanish: "rio", english: "river" },
{ spanish: "mar", english: "sea" },
{ spanish: "pais", english: "country" },
{ spanish: "ciudad", english: "city" },
{ spanish: "pueblo", english: "town" },

// PEOPLE / SOCIAL
{ spanish: "persona", english: "person" },
{ spanish: "grupo", english: "group" },
{ spanish: "equipo", english: "team" },
{ spanish: "familia", english: "family" },
{ spanish: "padre", english: "father" },
{ spanish: "madre", english: "mother" },
{ spanish: "hermano", english: "brother" },
{ spanish: "hermana", english: "sister" },
{ spanish: "hijo", english: "son" },
{ spanish: "hija", english: "daughter" },

// TIME
{ spanish: "hora", english: "hour" },
{ spanish: "minuto", english: "minute" },
{ spanish: "segundo", english: "second" },
{ spanish: "semana", english: "week" },
{ spanish: "mes", english: "month" },

// EXTRA CONNECTORS (GOOD FOR CROSSWORDS)
{ spanish: "pero", english: "but" },
{ spanish: "y", english: "and" },
{ spanish: "o", english: "or" },
{ spanish: "con", english: "with" },
{ spanish: "sin", english: "without" },
{ spanish: "sobre", english: "about" },
{ spanish: "entre", english: "between" },
{ spanish: "hasta", english: "until" },
{ spanish: "desde", english: "from" },
{ spanish: "contra", english: "against" },
{ spanish: "buscar", english: "to search" },
{ spanish: "encontrar", english: "to find" },
{ spanish: "usar", english: "to use" },
{ spanish: "trabajar", english: "to work" },
{ spanish: "vivir", english: "to live" },
{ spanish: "abrir", english: "to open" },
{ spanish: "cerrar", english: "to close" },
{ spanish: "seguir", english: "to follow" },
{ spanish: "cambiar", english: "to change" },
{ spanish: "apagar", english: "to turn off" },
{ spanish: "encender", english: "to turn on" },
{ spanish: "esperar", english: "to wait" },
{ spanish: "alcanzar", english: "to reach" },
{ spanish: "mantener", english: "to maintain" },
{ spanish: "comenzar", english: "to begin" },
{ spanish: "terminar", english: "to finish" },
{ spanish: "volver", english: "to return" },
{ spanish: "quitar", english: "to remove" },
{ spanish: "agregar", english: "to add" },
{ spanish: "servir", english: "to serve" },
{ spanish: "abrir", english: "to open" },
{ spanish: "cerrar", english: "to close" },

// MORE COMMON NOUNS
{ spanish: "idea", english: "idea" },
{ spanish: "problema", english: "problem" },
{ spanish: "solucion", english: "solution" },
{ spanish: "programa", english: "program" },
{ spanish: "sistema", english: "system" },
{ spanish: "nivel", english: "level" },
{ spanish: "grupo", english: "group" },
{ spanish: "equipo", english: "team" },
{ spanish: "resultado", english: "result" },
{ spanish: "proceso", english: "process" },
{ spanish: "control", english: "control" },
{ spanish: "energia", english: "energy" },
{ spanish: "fuerza", english: "force" },
{ spanish: "valor", english: "value" },
{ spanish: "precio", english: "price" },
{ spanish: "costo", english: "cost" },
{ spanish: "mercado", english: "market" },
{ spanish: "servicio", english: "service" },
{ spanish: "cliente", english: "client" },
{ spanish: "usuario", english: "user" },
{ spanish: "producto", english: "product" },

// MORE ADJECTIVES
{ spanish: "importante", english: "important" },
{ spanish: "necesario", english: "necessary" },
{ spanish: "posible", english: "possible" },
{ spanish: "imposible", english: "impossible" },
{ spanish: "probable", english: "probable" },
{ spanish: "seguro", english: "sure" },
{ spanish: "cierto", english: "certain" },
{ spanish: "claro", english: "clear" },
{ spanish: "oscuro", english: "dark" },
{ spanish: "simple", english: "simple" },
{ spanish: "complejo", english: "complex" },
{ spanish: "correcto", english: "correct" },
{ spanish: "incorrecto", english: "incorrect" },

// MORE ADVERBS
{ spanish: "rapidamente", english: "quickly" },
{ spanish: "lentamente", english: "slowly" },
{ spanish: "facilmente", english: "easily" },
{ spanish: "dificilmente", english: "with difficulty" },
{ spanish: "generalmente", english: "generally" },
{ spanish: "normalmente", english: "normally" },
{ spanish: "especialmente", english: "especially" },
{ spanish: "simplemente", english: "simply" },

// QUESTION WORDS
{ spanish: "que", english: "what" },
{ spanish: "quien", english: "who" },
{ spanish: "donde", english: "where" },
{ spanish: "cuando", english: "when" },
{ spanish: "como", english: "how" },
{ spanish: "por que", english: "why" },
{ spanish: "cual", english: "which" },
{ spanish: "cuanto", english: "how much" },

// COLORS
{ spanish: "rojo", english: "red" },
{ spanish: "azul", english: "blue" },
{ spanish: "verde", english: "green" },
{ spanish: "amarillo", english: "yellow" },
{ spanish: "negro", english: "black" },
{ spanish: "blanco", english: "white" },
{ spanish: "gris", english: "gray" },
{ spanish: "marron", english: "brown" },

// WEATHER
{ spanish: "clima", english: "weather" },
{ spanish: "lluvia", english: "rain" },
{ spanish: "nieve", english: "snow" },
{ spanish: "viento", english: "wind" },
{ spanish: "sol", english: "sun" },
{ spanish: "cielo", english: "sky" },
{ spanish: "nube", english: "cloud" },

// BODY
{ spanish: "cabeza", english: "head" },
{ spanish: "ojo", english: "eye" },
{ spanish: "nariz", english: "nose" },
{ spanish: "boca", english: "mouth" },
{ spanish: "brazo", english: "arm" },
{ spanish: "pierna", english: "leg" },
{ spanish: "pie", english: "foot" },
{ spanish: "corazon", english: "heart" },

// EXTRA GOOD CROSSWORD WORDS
{ spanish: "poder", english: "to be able" },
{ spanish: "deber", english: "must" },
{ spanish: "haber", english: "to have (aux)" },
{ spanish: "tener", english: "to have" },
{ spanish: "hacer", english: "to make" },
{ spanish: "decir", english: "to say" },
{ spanish: "ir", english: "to go" },
{ spanish: "ver", english: "to see" },
{ spanish: "dar", english: "to give" },

// SHORT HIGH-UTILITY WORDS (GREAT FOR CROSSINGS)
{ spanish: "uno", english: "one" },
{ spanish: "dos", english: "two" },
{ spanish: "tres", english: "three" },
{ spanish: "mas", english: "more" },
{ spanish: "menos", english: "less" },
{ spanish: "todo", english: "all" },
{ spanish: "nada", english: "nothing" },
{ spanish: "algo", english: "something" },
{ spanish: "otro", english: "other" },
{ spanish: "mismo", english: "same" },
{ spanish: "nuevo", english: "new" },
{ spanish: "viejo", english: "old" },
{ spanish: "aceptar", english: "to accept" },
{ spanish: "rechazar", english: "to reject" },
{ spanish: "descubrir", english: "to discover" },
{ spanish: "desarrollar", english: "to develop" },
{ spanish: "mejorar", english: "to improve" },
{ spanish: "reducir", english: "to reduce" },
{ spanish: "aumentar", english: "to increase" },
{ spanish: "decidir", english: "to decide" },
{ spanish: "elegir", english: "to choose" },
{ spanish: "olvidarse", english: "to forget oneself" },
{ spanish: "preparar", english: "to prepare" },
{ spanish: "organizar", english: "to organize" },
{ spanish: "planear", english: "to plan" },
{ spanish: "participar", english: "to participate" },
{ spanish: "ganarse", english: "to earn" },
{ spanish: "permitir", english: "to allow" },
{ spanish: "prohibir", english: "to prohibit" },
{ spanish: "evitar", english: "to avoid" },
{ spanish: "incluir", english: "to include" },
{ spanish: "excluir", english: "to exclude" },
{ spanish: "comparar", english: "to compare" },
{ spanish: "medir", english: "to measure" },
{ spanish: "pesar", english: "to weigh" },
{ spanish: "contener", english: "to contain" },
{ spanish: "pertenecer", english: "to belong" },

// NOUNS (NEW SET)
{ spanish: "archivo", english: "file" },
{ spanish: "mensaje", english: "message" },
{ spanish: "correo", english: "mail" },
{ spanish: "imagen", english: "image" },
{ spanish: "video", english: "video" },
{ spanish: "audio", english: "audio" },
{ spanish: "pagina", english: "page" },
{ spanish: "sitio", english: "site" },
{ spanish: "red", english: "network" },
{ spanish: "clave", english: "key" },
{ spanish: "codigo", english: "code" },
{ spanish: "error", english: "error" },
{ spanish: "fallo", english: "failure" },
{ spanish: "exito", english: "success" },
{ spanish: "meta", english: "goal" },
{ spanish: "objetivo", english: "objective" },
{ spanish: "plan", english: "plan" },
{ spanish: "tarea", english: "task" },
{ spanish: "proyecto", english: "project" },
{ spanish: "detalle", english: "detail" },
{ spanish: "ejercicio", english: "exercise" },
{ spanish: "practica", english: "practice" },
{ spanish: "nivel", english: "level" },
{ spanish: "grado", english: "grade" },
{ spanish: "titulo", english: "title" },

// FOOD (EXPANDED)
{ spanish: "pollo", english: "chicken" },
{ spanish: "pescado", english: "fish" },
{ spanish: "sopa", english: "soup" },
{ spanish: "ensalada", english: "salad" },
{ spanish: "postre", english: "dessert" },
{ spanish: "pastel", english: "cake" },
{ spanish: "galleta", english: "cookie" },
{ spanish: "chocolate", english: "chocolate" },
{ spanish: "helado", english: "ice cream" },
{ spanish: "mantequilla", english: "butter" },
{ spanish: "aceite", english: "oil" },
{ spanish: "vinagre", english: "vinegar" },

// TRANSPORT
{ spanish: "avion", english: "plane" },
{ spanish: "barco", english: "boat" },
{ spanish: "bicicleta", english: "bicycle" },
{ spanish: "metro", english: "subway" },
{ spanish: "taxi", english: "taxi" },
{ spanish: "autobus", english: "bus" },
{ spanish: "carretera", english: "road" },
{ spanish: "camino", english: "path" },

// MORE ADJECTIVES
{ spanish: "actual", english: "current" },
{ spanish: "anterior", english: "previous" },
{ spanish: "siguiente", english: "next" },
{ spanish: "final", english: "final" },
{ spanish: "inicial", english: "initial" },
{ spanish: "principal", english: "main" },
{ spanish: "secundario", english: "secondary" },
{ spanish: "general", english: "general" },
{ spanish: "particular", english: "particular" },
{ spanish: "unico", english: "unique" },
{ spanish: "doble", english: "double" },
{ spanish: "triple", english: "triple" },

// EMOTIONS
{ spanish: "amor", english: "love" },
{ spanish: "odio", english: "hate" },
{ spanish: "miedo", english: "fear" },
{ spanish: "alegria", english: "joy" },
{ spanish: "tristeza", english: "sadness" },
{ spanish: "enojo", english: "anger" },
{ spanish: "sorpresa", english: "surprise" },
{ spanish: "orgullo", english: "pride" },
{ spanish: "verguenza", english: "shame" },

// CLOTHING
{ spanish: "camisa", english: "shirt" },
{ spanish: "pantalon", english: "pants" },
{ spanish: "zapato", english: "shoe" },
{ spanish: "ropa", english: "clothes" },
{ spanish: "abrigo", english: "coat" },
{ spanish: "sombrero", english: "hat" },

// HOUSE ITEMS
{ spanish: "luz", english: "light" },
{ spanish: "fuego", english: "fire" },
{ spanish: "aire", english: "air" },
{ spanish: "suelo", english: "floor" },
{ spanish: "pared", english: "wall" },
{ spanish: "techo", english: "ceiling" },

// EXTRA SHORT WORDS (VERY IMPORTANT FOR CROSSWORDS)
{ spanish: "fin", english: "end" },
{ spanish: "sol", english: "sun" },
{ spanish: "mar", english: "sea" },
{ spanish: "voz", english: "voice" },
{ spanish: "luz", english: "light" },
{ spanish: "rey", english: "king" },
{ spanish: "ley", english: "law" },
{ spanish: "red", english: "net" },
{ spanish: "pie", english: "foot" },
{ spanish: "pan", english: "bread" }
];