const WORDS = [
    { "spanish": "que", "english": "which, that" },
{ "spanish": "ser", "english": "to be (permanent)" },
{ "spanish": "decir", "english": "say,  to tell" },
{ "spanish": "hacer", "english": "make,  to do" },
{ "spanish": "haber", "english": "to have" },
{ "spanish": "tener", "english": "to have" },
{ "spanish": "otro", "english": "another, other" },
{ "spanish": "por", "english": "for,  by,  through" },
{ "spanish": "con", "english": "with" },
{ "spanish": "todo", "english": "every, all" },
{ "spanish": "más", "english": "more" },
{ "spanish": "para", "english": "to,  for,  in order to" },
{ "spanish": "como", "english": "as, like" },
{ "spanish": "poder", "english": "can,  to be able to" },
{ "spanish": "dar", "english": "to give" },
{ "spanish": "estar", "english": "to be (temporary)" },
{ "spanish": "pero", "english": "yet, but,  except" },
{ "spanish": "qué", "english": "which?, what?,  how !" },
{ "spanish": "este", "english": "this[m][esta[f]]" },
{ "spanish": "entre", "english": "among,  between" },
{ "spanish": "pasar", "english": "spend[time],  to pass" },
{ "spanish": "uno", "english": "one" },
{ "spanish": "primero", "english": "ﬁrst" },
{ "spanish": "donde", "english": "where" },
{ "spanish": "porque", "english": "because" },
{ "spanish": "deber", "english": "ought to,  should,  to owe" },
{ "spanish": "ese", "english": "that[m][esa[f]]" },
{ "spanish": "nos", "english": "us[obj]" },
{ "spanish": "sobre", "english": "over,  on top of,  about" },
{ "spanish": "cuando", "english": "when" },
{ "spanish": "hombre", "english": "mankind, man,  husband" },
{ "spanish": "grande", "english": "great, large,  big" },
{ "spanish": "alguno", "english": "someone[pron], some" },
{ "spanish": "muy", "english": "really,  very" },
{ "spanish": "forma", "english": "shape, form,  way" },
{ "spanish": "cada", "english": "every, each" },
{ "spanish": "algo", "english": "somewhat, something" },
{ "spanish": "tres", "english": "three" },
{ "spanish": "dos", "english": "two" },
{ "spanish": "momento", "english": "time, moment" },
{ "spanish": "menos", "english": "fewer, less" },
{ "spanish": "hasta", "english": "up to,  until,  even" },
{ "spanish": "vez", "english": "time[speciﬁc occurrence]" },
{ "spanish": "así", "english": "like that" },
{ "spanish": "esto", "english": "this[n]" },
{ "spanish": "ver", "english": "to see" },
{ "spanish": "cierto", "english": "true,  sure, certain" },
{ "spanish": "mundo", "english": "world" },
{ "spanish": "poner", "english": "get ,  to put[on]" },
{ "spanish": "sin", "english": "without" },
{ "spanish": "punto", "english": "period,  dot, point" },
{ "spanish": "mucho", "english": "many, much,  a lot" },
{ "spanish": "después", "english": "after" },
{ "spanish": "cosa", "english": "thing" },
{ "spanish": "casi", "english": "nearly,  almost" },
{ "spanish": "llegar", "english": "to arrive" },
{ "spanish": "tan", "english": "as,  such,  too,  so" },
{ "spanish": "también", "english": "also" },
{ "spanish": "hablar", "english": "talk,  to speak" },
{ "spanish": "mujer", "english": "wife, woman" },
{ "spanish": "ella", "english": "[ellas]them[f], she" },
{ "spanish": "hora", "english": "time[speciﬁc], hour" },
{ "spanish": "ahora", "english": "now" },
{ "spanish": "propio", "english": "typical,  proper, own" },
{ "spanish": "saber", "english": "ﬁnd out,  to know[a fact]" },
{ "spanish": "tanto", "english": "so many, so much" },
{ "spanish": "pensar", "english": "to think" },
{ "spanish": "desde", "english": "since,  from" },
{ "spanish": "mejor", "english": "better , best" },
{ "spanish": "niño", "english": "littleboy, child" },
{ "spanish": "mismo", "english": "same" },
{ "spanish": "tipo", "english": "kind, type" },
{ "spanish": "pequeño", "english": "young, small, little" },
{ "spanish": "año", "english": "year" },
{ "spanish": "allí", "english": "over there,  there" },
{ "spanish": "parte", "english": "portion, part" },
{ "spanish": "vida", "english": "life" },
{ "spanish": "trabajo", "english": "effort,  job, work" },
{ "spanish": "querer", "english": "love,  to want" },
{ "spanish": "nombre", "english": "noun, name" },
{ "spanish": "casa", "english": "house" },
{ "spanish": "país", "english": "country" },
{ "spanish": "siempre", "english": "forever,  always" },
{ "spanish": "volver", "english": "to V again,  to return" },
{ "spanish": "tiempo", "english": "weather, time[general]" },
{ "spanish": "mayor", "english": "main,  older, larger" },
{ "spanish": "eso", "english": "that[n]" },
{ "spanish": "bajo", "english": "underneath,  under" },
{ "spanish": "nada", "english": "not]at all, nothing" },
{ "spanish": "persona", "english": "person" },
{ "spanish": "bien", "english": "well" },
{ "spanish": "nuestro", "english": "our" },
{ "spanish": "antes", "english": "before" },
{ "spanish": "historia", "english": "story, history" },
{ "spanish": "poco", "english": "few, little,  a littlebit" },
{ "spanish": "durante", "english": "for[time],  during" },
{ "spanish": "quien", "english": "whom, who" },
{ "spanish": "lugar", "english": "position, place" },
{ "spanish": "realidad", "english": "actuality, reality" },
{ "spanish": "presentar", "english": "present,  to introduce" },
{ "spanish": "conocer", "english": "to know[someone or place]" },
{ "spanish": "vivir", "english": "to live" },
{ "spanish": "hecho", "english": "happening, fact" },
{ "spanish": "entonces", "english": "then,  so" },
{ "spanish": "día", "english": "day" },
{ "spanish": "salir", "english": "go out,  to leave" },
{ "spanish": "llamar", "english": "name,  to call" },
{ "spanish": "cuatro", "english": "four" },
{ "spanish": "seguir", "english": "keep on,  to follow" },
{ "spanish": "recordar", "english": "remind,  to remember" },
{ "spanish": "cambio", "english": "change" },
{ "spanish": "blanco", "english": "white" },
{ "spanish": "sacar", "english": "to take out" },
{ "spanish": "conseguir", "english": "obtain,  acquire,  to get" },
{ "spanish": "aquel", "english": "that[over there]" },
{ "spanish": "empezar", "english": "start,  to begin" },
{ "spanish": "modo", "english": "manner, way" },
{ "spanish": "llevar", "english": "carry,  to take" },
{ "spanish": "amigo", "english": "friend" },
{ "spanish": "tema", "english": "topic,  subject, theme" },
{ "spanish": "creer", "english": "think,  to believe" },
{ "spanish": "dejar", "english": "leave,  to let" },
{ "spanish": "existir", "english": "to exist" },
{ "spanish": "verdad", "english": "truth" },
{ "spanish": "aquí", "english": "here" },
{ "spanish": "ciudad", "english": "city" },
{ "spanish": "general", "english": "general" },
{ "spanish": "sólo", "english": "just,  only" },
{ "spanish": "aunque", "english": "even though, although" },
{ "spanish": "calle", "english": "street" },
{ "spanish": "parecer", "english": "look like,  to seem" },
{ "spanish": "manera", "english": "manner, way" },
{ "spanish": "recibir", "english": "to receive" },
{ "spanish": "quedar", "english": "stay,  to remain" },
{ "spanish": "preguntar", "english": "to ask[a question]" },
{ "spanish": "trabajar", "english": "to work" },
{ "spanish": "esperar", "english": "expect,  hope[for],  to wait" },
{ "spanish": "aceptar", "english": "to accept" },
{ "spanish": "formar", "english": "to form" },
{ "spanish": "hacia", "english": "towards,  toward" },
{ "spanish": "sino", "english": "except, but,  rather" },
{ "spanish": "aún", "english": "yet,  still" },
{ "spanish": "nunca", "english": "ever,  never" },
{ "spanish": "bueno", "english": "good" },
{ "spanish": "caso", "english": "occasion, case" },
{ "spanish": "mano", "english": "hand" },
{ "spanish": "nuevo", "english": "new" },
{ "spanish": "pueblo", "english": "village, people" },
{ "spanish": "cuanto", "english": "regarding, en cuanto a: in terms of" },
{ "spanish": "solo", "english": "alone, lonely" },
{ "spanish": "sentir", "english": "regret,  to feel" },
{ "spanish": "medio", "english": "middle, half" },
{ "spanish": "alcanzar", "english": "catch up with,  to reach" },
{ "spanish": "cuyo", "english": "whose" },
{ "spanish": "jugar", "english": "game],  to play[sport" },
{ "spanish": "fuerza", "english": "power,  force, strength" },
{ "spanish": "tarde", "english": "evening, afternoon" },
{ "spanish": "tal", "english": "such[a]" },
{ "spanish": "posible", "english": "possible" },
{ "spanish": "ejemplo", "english": "example" },
{ "spanish": "tratar", "english": "deal with,  treat,  to try" },
{ "spanish": "crear", "english": "to create" },
{ "spanish": "encontrar", "english": "to ﬁnd" },
{ "spanish": "ante", "english": "in the presence of,  before" },
{ "spanish": "ser", "english": "being" },
{ "spanish": "aire", "english": "appearance,  wind, air" },
{ "spanish": "venir", "english": "to come" },
{ "spanish": "escribir", "english": "to write" },
{ "spanish": "viejo", "english": "aged, old" },
{ "spanish": "palabra", "english": "word" },
{ "spanish": "obra", "english": "deed,  book, work" },
{ "spanish": "ninguno", "english": "nobody[pron],  none, no" },
{ "spanish": "pues", "english": "well then, then" },
{ "spanish": "situación", "english": "situation" },
{ "spanish": "campo", "english": "country, ﬁeld" },
{ "spanish": "luego", "english": "afterwards,  later" },
{ "spanish": "dentro", "english": "inside" },
{ "spanish": "cuenta", "english": "account, bill" },
{ "spanish": "cuerpo", "english": "body" },
{ "spanish": "segundo", "english": "second" },
{ "spanish": "cual", "english": "whom,  who, which" },
{ "spanish": "cambiar", "english": "to change" },
{ "spanish": "ocurrir", "english": "occur,  to happen" },
{ "spanish": "luz", "english": "light" },
{ "spanish": "anterior", "english": "preceding, previous" },
{ "spanish": "menor", "english": "youngest, younger" },
{ "spanish": "aparecer", "english": "to appear" },
{ "spanish": "éste", "english": "[ésta[f]], this one[m]" },
{ "spanish": "gente", "english": "people" },
{ "spanish": "tomar", "english": "drink,  to take" },
{ "spanish": "escuchar", "english": "to listen to" },
{ "spanish": "gracia", "english": "favor,  grace, pl]thank you" },
{ "spanish": "además", "english": "besides,  as well,  also" },
{ "spanish": "gustar", "english": "to be pleasing to" },
{ "spanish": "varios", "english": "various, several" },
{ "spanish": "cabeza", "english": "head[part of body]" },
{ "spanish": "efecto", "english": "effect" },
{ "spanish": "mantener", "english": "maintain,  to keep" },
{ "spanish": "santo", "english": "saint[m]" },
{ "spanish": "quizás", "english": "maybe,  perhaps" },
{ "spanish": "servicio", "english": "helpfulness, service" },
{ "spanish": "cinco", "english": "ﬁve" },
{ "spanish": "tierra", "english": "ground,  land, earth" },
{ "spanish": "cómo", "english": "how?" },
{ "spanish": "comprender", "english": "to understand" },
{ "spanish": "comer", "english": "to eat" },
{ "spanish": "contar", "english": "count,  to tell" },
{ "spanish": "mil", "english": "thousand" },
{ "spanish": "programa", "english": "plan, program" },
{ "spanish": "distinto", "english": "different, distinct" },
{ "spanish": "ahí", "english": "there" },
{ "spanish": "último", "english": "ﬁnal, last" },
{ "spanish": "don", "english": "gift,  Mr, courtesy title[m]" },
{ "spanish": "pedir", "english": "request,  to ask for" },
{ "spanish": "agua", "english": "[el]water" },
{ "spanish": "abrir", "english": "to open" },
{ "spanish": "valor", "english": "worth, value" },
{ "spanish": "embargo", "english": "sin embargo: nevertheless" },
{ "spanish": "fácil", "english": "easy" },
{ "spanish": "nadie", "english": "anybody, nobody" },
{ "spanish": "contrario", "english": "opposite, contrary" },
{ "spanish": "imaginar", "english": "to imagine" },
{ "spanish": "junto", "english": "next to,  together with" },
{ "spanish": "partido", "english": "[sports]match,  group, party" },
{ "spanish": "ciento", "english": "hundred" },
{ "spanish": "leer", "english": "to read" },
{ "spanish": "pregunta", "english": "question" },
{ "spanish": "español", "english": "Spanish" },
{ "spanish": "hoy", "english": "nowadays,  today" },
{ "spanish": "mesa", "english": "board, table" },
{ "spanish": "cualquier", "english": "anyone[pron], any" },
{ "spanish": "seguridad", "english": "safety,  security" },
{ "spanish": "mirar", "english": "watch,  to look" },
{ "spanish": "estudiar", "english": "to study" },
{ "spanish": "lado", "english": "side" },
{ "spanish": "mientras", "english": "as long as,  whereas, while" },
{ "spanish": "base", "english": "basis, base" },
{ "spanish": "época", "english": "period,  age, time" },
{ "spanish": "claro", "english": "clear" },
{ "spanish": "clase", "english": "order,  class, kind" },
{ "spanish": "quién", "english": "whom?, who?" },
{ "spanish": "alto", "english": "high, tall" },
{ "spanish": "problema", "english": "problem" },
{ "spanish": "antiguo", "english": "former,  ancient, old" },
{ "spanish": "vista", "english": "sight, view" },
{ "spanish": "obtener", "english": "to obtain" },
{ "spanish": "centro", "english": "downtown,  middle, center" },
{ "spanish": "carta", "english": "[playing]card,  letter" },
{ "spanish": "pobre", "english": "poor" },
{ "spanish": "contra", "english": "opposite,  against" },
{ "spanish": "hijo", "english": "[pl]children, son" },
{ "spanish": "mostrar", "english": "to show" },
{ "spanish": "interés", "english": "interest" },
{ "spanish": "término", "english": "end,  term[language]" },
{ "spanish": "buscar", "english": "to look for" },
{ "spanish": "especial", "english": "special" },
{ "spanish": "político", "english": "political" },
{ "spanish": "desear", "english": "wish for,  desire,  to want" },
{ "spanish": "necesario", "english": "necessary" },
{ "spanish": "terminar", "english": "end,  to ﬁnish" },
{ "spanish": "perder", "english": "miss,  to lose" },
{ "spanish": "deseo", "english": "wish,  desire" },
{ "spanish": "padre", "english": "father" },
{ "spanish": "tampoco", "english": "either,  nor,  neither" },
{ "spanish": "señor", "english": "lord,  Mr, sir" },
{ "spanish": "resultar", "english": "turn out,  to result" },
{ "spanish": "función", "english": "meeting,  function" },
{ "spanish": "noche", "english": "evening, night" },
{ "spanish": "largo", "english": "long" },
{ "spanish": "familia", "english": "family" },
{ "spanish": "seis", "english": "six" },
{ "spanish": "bajo", "english": "low, short" },
{ "spanish": "producir", "english": "cause,  to produce" },
{ "spanish": "segundo", "english": "second" },
{ "spanish": "inglés", "english": "English" },
{ "spanish": "negro", "english": "black" },
{ "spanish": "miedo", "english": "fear" },
{ "spanish": "entrar", "english": "to enter" },
{ "spanish": "dedicar", "english": "devote,  to dedicate" },
{ "spanish": "paso", "english": "pace, step" },
{ "spanish": "usted", "english": "formal], you[subj" },
{ "spanish": "río", "english": "river" },
{ "spanish": "dirección", "english": "address,  direction" },
{ "spanish": "cuestión", "english": "matter, question" },
{ "spanish": "derecho", "english": "law,  justice, right" },
{ "spanish": "malo", "english": "bad" },
{ "spanish": "principio", "english": "principle, beginning" },
{ "spanish": "guerra", "english": "warfare, war" },
{ "spanish": "único", "english": "sole,  unique, only" },
{ "spanish": "avanzar", "english": "progress,  to advance" },
{ "spanish": "entender", "english": "to understand" },
{ "spanish": "lanzar", "english": "launch,  to throw" },
{ "spanish": "diferencia", "english": "difference" },
{ "spanish": "bueno", "english": "well…" },
{ "spanish": "propiedad", "english": "property" },
{ "spanish": "repetir", "english": "to repeat" },
{ "spanish": "viaje", "english": "trip, travel" },
{ "spanish": "nosotros", "english": "we[subj]" },
{ "spanish": "diez", "english": "ten" },
{ "spanish": "indicar", "english": "to indicate" },
{ "spanish": "capaz", "english": "able, capable" },
{ "spanish": "todavía", "english": "yet,  still" },
{ "spanish": "servir", "english": "to serve" },
{ "spanish": "joven", "english": "young person,  teenager" },
{ "spanish": "comenzar", "english": "start,  to begin" },
{ "spanish": "idea", "english": "idea" },
{ "spanish": "peso", "english": "load,  weight, peso[money]" },
{ "spanish": "ocho", "english": "eight" },
{ "spanish": "estudio", "english": "learning, study" },
{ "spanish": "grupo", "english": "group" },
{ "spanish": "decidir", "english": "to decide" },
{ "spanish": "considerar", "english": "to consider" },
{ "spanish": "allá", "english": "over there,  there" },
{ "spanish": "mal", "english": "badly" },
{ "spanish": "anunciar", "english": "advertise,  to announce" },
{ "spanish": "sociedad", "english": "society" },
{ "spanish": "política", "english": "policy,  politics" },
{ "spanish": "detener", "english": "detain,  to stop" },
{ "spanish": "camino", "english": "path,  route, road" },
{ "spanish": "duda", "english": "doubt" },
{ "spanish": "dinero", "english": "money" },
{ "spanish": "millón", "english": "fortune,  million" },
{ "spanish": "abandonar", "english": "leave[a place],  to abandon" },
{ "spanish": "pieza", "english": "part,  piece" },
{ "spanish": "claro", "english": "clearly,  of course" },
{ "spanish": "movimiento", "english": "movement" },
{ "spanish": "sitio", "english": "space,  place" },
{ "spanish": "arriba", "english": "above,  up" },
{ "spanish": "crecer", "english": "increase,  to grow" },
{ "spanish": "siglo", "english": "age, century" },
{ "spanish": "necesidad", "english": "need, necessity" },
{ "spanish": "verdadero", "english": "real, true" },
{ "spanish": "doctor", "english": "doctor" },
{ "spanish": "natural", "english": "natural" },
{ "spanish": "contestar", "english": "reply,  to answer" },
{ "spanish": "mercado", "english": "market" },
{ "spanish": "reconocer", "english": "admit,  to recognize" },
{ "spanish": "importante", "english": "important" },
{ "spanish": "recurso", "english": "means,  recourse,  resource" },
{ "spanish": "intentar", "english": "attempt,  to try" },
{ "spanish": "realizar", "english": "carry out,  to fulﬁll" },
{ "spanish": "mes", "english": "month" },
{ "spanish": "golpe", "english": "punch,  strike,  hit" },
{ "spanish": "grado", "english": "grade,  degree" },
{ "spanish": "morir", "english": "to die" },
{ "spanish": "ojo", "english": "eye" },
{ "spanish": "permitir", "english": "permit,  to allow" },
{ "spanish": "humano", "english": "human" },
{ "spanish": "físico", "english": "physical" },
{ "spanish": "convertir", "english": "become,  change,  to convert" },
{ "spanish": "voz", "english": "voice" },
{ "spanish": "incluso", "english": "even ,  including" },
{ "spanish": "bastante", "english": "quite a bit ,  fairly, rather" },
{ "spanish": "profundo", "english": "profound, deep" },
{ "spanish": "minuto", "english": "minute" },
{ "spanish": "suelo", "english": "ﬂoor, ground" },
{ "spanish": "traer", "english": "carry,  to bring" },
{ "spanish": "asegurar", "english": "insure,  secure,  to assure" },
{ "spanish": "brazo", "english": "arm" },
{ "spanish": "uso", "english": "use" },
{ "spanish": "parecido", "english": "similar" },
{ "spanish": "imagen", "english": "picture, image" },
{ "spanish": "origen", "english": "cause,  origin" },
{ "spanish": "caer", "english": "to fall" },
{ "spanish": "relación", "english": "relation, relationship" },
{ "spanish": "apoyar", "english": "lean on,  to support" },
{ "spanish": "sangre", "english": "blood" },
{ "spanish": "demás", "english": "others, the rest" },
{ "spanish": "igual", "english": "same[as], equal" },
{ "spanish": "edad", "english": "age" },
{ "spanish": "cantidad", "english": "amount, quantity" },
{ "spanish": "actuar", "english": "to act" },
{ "spanish": "comprobar", "english": "prove,  to verify" },
{ "spanish": "comprar", "english": "to buy" },
{ "spanish": "según", "english": "according to" },
{ "spanish": "observar", "english": "to observe" },
{ "spanish": "frente", "english": "frente a: across from, al frente: facing" },
{ "spanish": "lograr", "english": "manage,  get,  to achieve" },
{ "spanish": "puerta", "english": "door" },
{ "spanish": "completo", "english": "complete" },
{ "spanish": "moderno", "english": "modern" },
{ "spanish": "atravesar", "english": "to cross" },
{ "spanish": "maestro", "english": "master,  teacher[m]" },
{ "spanish": "oír", "english": "to hear" },
{ "spanish": "adelante", "english": "further,  forward" },
{ "spanish": "diferente", "english": "separate, different" },
{ "spanish": "delante", "english": "ahead, [in]front[of]" },
{ "spanish": "sentido", "english": "feeling, sense" },
{ "spanish": "imposible", "english": "impossible" },
{ "spanish": "solamente", "english": "only" },
{ "spanish": "libro", "english": "book" },
{ "spanish": "lenguaje", "english": "speech,  language" },
{ "spanish": "ello", "english": "it[subj-n]" },
{ "spanish": "difícil", "english": "hard, difﬁcult" },
{ "spanish": "ofrecer", "english": "present,  to offer" },
{ "spanish": "sistema", "english": "system" },
{ "spanish": "enorme", "english": "vast, enormous" },
{ "spanish": "realmente", "english": "in fact,  actually,  really" },
{ "spanish": "social", "english": "social" },
{ "spanish": "abierto", "english": "unlocked, open" },
{ "spanish": "subir", "english": "to go up" },
{ "spanish": "evitar", "english": "prevent,  to avoid" },
{ "spanish": "superar", "english": "surpass,  to overcome" },
{ "spanish": "papel", "english": "part,  role, paper" },
{ "spanish": "surgir", "english": "spring[forth],  to appear" },
{ "spanish": "rojo", "english": "red" },
{ "spanish": "pasado", "english": "last, past" },
{ "spanish": "favor", "english": "beneﬁt, favor" },
{ "spanish": "siguiente", "english": "next, following" },
{ "spanish": "semana", "english": "week" },
{ "spanish": "miembro", "english": "limb,  member" },
{ "spanish": "suponer", "english": "assume,  to suppose" },
{ "spanish": "puro", "english": "clean,  pure" },
{ "spanish": "carga", "english": "cargo,  charge,  load" },
{ "spanish": "calor", "english": "warmth,  heat" },
{ "spanish": "enemigo", "english": "enemy" },
{ "spanish": "tender", "english": "lay out,  to tend to" },
{ "spanish": "serio", "english": "serious" },
{ "spanish": "madre", "english": "mother" },
{ "spanish": "mover", "english": "incite,  to move" },
{ "spanish": "demasiado", "english": "too many, too much" },
{ "spanish": "ganar", "english": "earn,  to win" },
{ "spanish": "lleno", "english": "ﬁlled,  full" },
{ "spanish": "altura", "english": "altitude,  height" },
{ "spanish": "civil", "english": "civil" },
{ "spanish": "niña", "english": "young girl,  child" },
{ "spanish": "cara", "english": "expression, face" },
{ "spanish": "metro", "english": "subway,  meter" },
{ "spanish": "cuidado", "english": "carefulness,  care" },
{ "spanish": "levantar", "english": "lift,  to raise" },
{ "spanish": "dios", "english": "divinity, god" },
{ "spanish": "hermano", "english": "[pl]siblings,  brother" },
{ "spanish": "participar", "english": "to participate" },
{ "spanish": "dónde", "english": "where?" },
{ "spanish": "explicar", "english": "to explain" },
{ "spanish": "libertad", "english": "liberty, freedom" },
{ "spanish": "naturaleza", "english": "character,  nature" },
{ "spanish": "sol", "english": "sun" },
{ "spanish": "popular", "english": "popular" },
{ "spanish": "utilizar", "english": "utilize,  to use" },
{ "spanish": "voluntad", "english": "intention,  willpower,  will" },
{ "spanish": "verde", "english": "green" },
{ "spanish": "extraño", "english": "foreign,  strange" },
{ "spanish": "accidente", "english": "irregularity,  accident" },
{ "spanish": "económico", "english": "economic" },
{ "spanish": "rico", "english": "tasty,  rich" },
{ "spanish": "olvidar", "english": "to forget" },
{ "spanish": "zona", "english": "zone, area" },
{ "spanish": "fuera", "english": "away,  outside,  out" },
{ "spanish": "número", "english": "number" },
{ "spanish": "estado", "english": "status,  condition, state" },
{ "spanish": "través", "english": "through,  over,  a través: across" },
{ "spanish": "especie", "english": "species,  sort, kind" },
{ "spanish": "empresa", "english": "venture,  company,  ﬁrm" },
{ "spanish": "cincuenta", "english": "ﬁfty" },
{ "spanish": "nacer", "english": "to be born" },
{ "spanish": "lengua", "english": "strip[of land],  tongue,  language" },
{ "spanish": "usar", "english": "to use" },
{ "spanish": "pagar", "english": "to pay" },
{ "spanish": "tamaño", "english": "dimension,  size" },
{ "spanish": "revista", "english": "journal,  magazine" },
{ "spanish": "cerrado", "english": "closed" },
{ "spanish": "frontera", "english": "frontier,  border" },
{ "spanish": "faltar", "english": "to be lacking" },
{ "spanish": "animal", "english": "animal" },
{ "spanish": "acción", "english": "deed,  act, action" },
{ "spanish": "correr", "english": "to run" },
{ "spanish": "corazón", "english": "core,  heart" },
{ "spanish": "aprender", "english": "to learn" },
{ "spanish": "enseñar", "english": "show,  to teach" },
{ "spanish": "quitar", "english": "take away,  to remove" },
{ "spanish": "mensaje", "english": "message" },
{ "spanish": "analizar", "english": "to analyze" },
{ "spanish": "bien", "english": "beneﬁt,  property,  goods" },
{ "spanish": "público", "english": "public" },
{ "spanish": "elegir", "english": "elect,  to choose" },
{ "spanish": "región", "english": "region" },
{ "spanish": "policía", "english": "police ofﬁcer,  police force,  police" },
{ "spanish": "comienzo", "english": "beginning,  start" },
{ "spanish": "suceder", "english": "to happen" },
{ "spanish": "fondo", "english": "end, bottom" },
{ "spanish": "amor", "english": "love" },
{ "spanish": "resolver", "english": "work out,  settle,  to resolve" },
{ "spanish": "vecino", "english": "neighbor" },
{ "spanish": "actividad", "english": "action, activity" },
{ "spanish": "corto", "english": "brief,  short" },
{ "spanish": "derecha", "english": "right hand,  right" },
{ "spanish": "dirigir", "english": "manage,  to direct" },
{ "spanish": "unir", "english": "join[together],  to unite" },
{ "spanish": "muerte", "english": "death" },
{ "spanish": "plantear", "english": "present,  to propose" },
{ "spanish": "gobierno", "english": "government" },
{ "spanish": "compartir", "english": "to share" },
{ "spanish": "sentar", "english": "seat,  to sit[down]" },
{ "spanish": "ley", "english": "rule,  bill, law" },
{ "spanish": "plano", "english": "level,  map,  plane" },
{ "spanish": "tocar", "english": "play[instrument],  to touch" },
{ "spanish": "terrible", "english": "terrible" },
{ "spanish": "línea", "english": "course, line" },
{ "spanish": "temprano", "english": "early" },
{ "spanish": "andar", "english": "function,  to walk" },
{ "spanish": "resultado", "english": "outcome, result" },
{ "spanish": "espacio", "english": "room, space" },
{ "spanish": "constituir", "english": "consist of,  to constitute" },
{ "spanish": "carrera", "english": "race,  course, career" },
{ "spanish": "mañana", "english": "tomorrow, morning" },
{ "spanish": "frase", "english": "phrase" },
{ "spanish": "reunión", "english": "reunion,  meeting" },
{ "spanish": "cultura", "english": "culture" },
{ "spanish": "enfermedad", "english": "sickness,  illness" },
{ "spanish": "resto", "english": "leftover,  remainder, rest" },
{ "spanish": "literatura", "english": "literature" },
{ "spanish": "sueño", "english": "sleep,  dream" },
{ "spanish": "importar", "english": "import,  to matter" },
{ "spanish": "dispuesto", "english": "ready,  willing" },
{ "spanish": "compañero", "english": "classmate,  companion" },
{ "spanish": "depender", "english": "to depend on" },
{ "spanish": "poder", "english": "power" },
{ "spanish": "verano", "english": "summer" },
{ "spanish": "cumplir", "english": "to fulﬁll" },
{ "spanish": "jamás", "english": "never" },
{ "spanish": "tercero", "english": "third" },
{ "spanish": "continuar", "english": "to continue" },
{ "spanish": "arma", "english": "[el]weapon" },
{ "spanish": "pie", "english": "base, foot" },
{ "spanish": "esfuerzo", "english": "endeavor, effort" },
{ "spanish": "condición", "english": "condition" },
{ "spanish": "contribuir", "english": "to contribute" },
{ "spanish": "cortar", "english": "to cut" },
{ "spanish": "atender", "english": "attend to,  to serve" },
{ "spanish": "ayudar", "english": "to help" },
{ "spanish": "color", "english": "color" },
{ "spanish": "pasado", "english": "past" },
{ "spanish": "lista", "english": "roll,  roster,  list" },
{ "spanish": "famoso", "english": "well-known,  famous" },
{ "spanish": "falta", "english": "shortage, lack" },
{ "spanish": "ocasión", "english": "occasion, opportunity" },
{ "spanish": "visitar", "english": "to visit" },
{ "spanish": "premio", "english": "reward,  prize" },
{ "spanish": "visita", "english": "guest,  visitor,  visit" },
{ "spanish": "dedo", "english": "digit,  toe,  ﬁnger" },
{ "spanish": "quince", "english": "ﬁfteen" },
{ "spanish": "demostrar", "english": "demonstrate,  to show" },
{ "spanish": "despertar", "english": "arouse,  to wake[up]" },
{ "spanish": "existencia", "english": "life,  existence" },
{ "spanish": "mente", "english": "mind" },
{ "spanish": "mayoría", "english": "majority" },
{ "spanish": "examen", "english": "exam,  examination" },
{ "spanish": "teléfono", "english": "telephone,  phone" },
{ "spanish": "juego", "english": "sport,  play, game" },
{ "spanish": "mío", "english": "mine" },
{ "spanish": "acto", "english": "action,  act" },
{ "spanish": "rama", "english": "limb,  bough,  branch" },
{ "spanish": "libre", "english": "vacant, free" },
{ "spanish": "recoger", "english": "to pick up" },
{ "spanish": "inmediato", "english": "immediate" },
{ "spanish": "nivel", "english": "level" },
{ "spanish": "ciencia", "english": "knowledge,  science" },
{ "spanish": "ayuda", "english": "aid,  help" },
{ "spanish": "ambiente", "english": "atmosphere,  environment" },
{ "spanish": "imponer", "english": "enforce,  to impose" },
{ "spanish": "alemán", "english": "German" },
{ "spanish": "casar", "english": "to marry" },
{ "spanish": "masa", "english": "bulk,  crowd,  dough,  mass" },
{ "spanish": "clásico", "english": "classic" },
{ "spanish": "futuro", "english": "future" },
{ "spanish": "loco", "english": "insane,  crazy" },
{ "spanish": "atención", "english": "attention" },
{ "spanish": "pegar", "english": "stick[on],  to hit" },
{ "spanish": "comida", "english": "meal,  food" },
{ "spanish": "capacidad", "english": "capacity" },
{ "spanish": "ambos", "english": "both" },
{ "spanish": "concreto", "english": "real,  concrete" },
{ "spanish": "ocupar", "english": "use,  to occupy" },
{ "spanish": "entrada", "english": "admission ticket,  entrance" },
{ "spanish": "objetivo", "english": "objective" },
{ "spanish": "entregar", "english": "to deliver" },
{ "spanish": "teatro", "english": "drama,  theater" },
{ "spanish": "cuál", "english": "which?" },
{ "spanish": "volumen", "english": "volume" },
{ "spanish": "francés", "english": "French" },
{ "spanish": "cerca", "english": "near,  close" },
{ "spanish": "nueve", "english": "nine" },
{ "spanish": "descubrir", "english": "to discover" },
{ "spanish": "pintura", "english": "paint,  painting" },
{ "spanish": "determinar", "english": "decide,  to determine" },
{ "spanish": "materia", "english": "subject,  matter" },
{ "spanish": "televisión", "english": "television,  TV" },
{ "spanish": "autoridad", "english": "authority" },
{ "spanish": "hogar", "english": "hearth,  home" },
{ "spanish": "material", "english": "element,  material" },
{ "spanish": "cuándo", "english": "when?" },
{ "spanish": "pintar", "english": "to paint" },
{ "spanish": "energía", "english": "power,  energy" },
{ "spanish": "recuerdo", "english": "keepsake,  memory" },
{ "spanish": "conservar", "english": "preserve,  to conserve" },
{ "spanish": "meter", "english": "to put[into]" },
{ "spanish": "santa", "english": "saint[f]" },
{ "spanish": "común", "english": "common" },
{ "spanish": "viajar", "english": "to travel" },
{ "spanish": "discutir", "english": "discuss,  to argue" },
{ "spanish": "pasión", "english": "desire,  passion" },
{ "spanish": "vino", "english": "wine" },
{ "spanish": "alma", "english": "[el]soul" },
{ "spanish": "teoría", "english": "theory" },
{ "spanish": "temer", "english": "to fear" },
{ "spanish": "artista", "english": "performer,  artist" },
{ "spanish": "junto", "english": "together" },
{ "spanish": "fecha", "english": "day,  date" },
{ "spanish": "sufrir", "english": "undergo,  to suffer" },
{ "spanish": "cielo", "english": "ceiling,  heaven,  sky" },
{ "spanish": "temor", "english": "fear" },
{ "spanish": "jefe", "english": "manager,  boss,  leader" },
{ "spanish": "capítulo", "english": "chapter" },
{ "spanish": "techo", "english": "roof" },
{ "spanish": "presencia", "english": "appearance,  presence" },
{ "spanish": "separar", "english": "to separate" },
{ "spanish": "decisión", "english": "decision" },
{ "spanish": "echar", "english": "cast,  to throw" },
{ "spanish": "nacional", "english": "national" },
{ "spanish": "objeto", "english": "thing, object" },
{ "spanish": "autor", "english": "author,  writer" },
{ "spanish": "aspecto", "english": "appearance, aspect" },
{ "spanish": "resistir", "english": "endure,  to resist" },
{ "spanish": "responder", "english": "respond,  to answer" },
{ "spanish": "encima", "english": "in addition,  on top,  above" },
{ "spanish": "acercar", "english": "to come near" },
{ "spanish": "preparar", "english": "to prepare" },
{ "spanish": "citar", "english": "quote,  to cite" },
{ "spanish": "extender", "english": "spread,  to extend" },
{ "spanish": "descansar", "english": "to rest" },
{ "spanish": "asunto", "english": "affair,  issue,  matter" },
{ "spanish": "facilidad", "english": "facility,  ease" },
{ "spanish": "preocupar", "english": "to worry" },
{ "spanish": "atrás", "english": "ago,  behind,  back" },
{ "spanish": "empleado", "english": "employee" },
{ "spanish": "pronto", "english": "quick,  soon" },
{ "spanish": "concepto", "english": "concept" },
{ "spanish": "grave", "english": "solemn,  serious" },
{ "spanish": "retirar", "english": "retire,  to take away" },
{ "spanish": "establecer", "english": "to establish" },
{ "spanish": "adquirir", "english": "get,  to acquire" },
{ "spanish": "costar", "english": "be hard,  to cost" },
{ "spanish": "mencionar", "english": "cite,  to mention" },
{ "spanish": "práctica", "english": "skill,  practice" },
{ "spanish": "publicar", "english": "to publish" },
{ "spanish": "idioma", "english": "[speciﬁc]language" },
{ "spanish": "aprovechar", "english": "to take advantage of" },
{ "spanish": "futuro", "english": "future" },
{ "spanish": "conclusión", "english": "end,  conclusion" },
{ "spanish": "vehículo", "english": "car,  vehicle" },
{ "spanish": "militar", "english": "military" },
{ "spanish": "compañía", "english": "company" },
{ "spanish": "curso", "english": "direction,  course" },
{ "spanish": "cine", "english": "US movie theater,  cinema" },
{ "spanish": "marcar", "english": "dial,  note,  to mark" },
{ "spanish": "comentario", "english": "comment,  remark" },
{ "spanish": "vivo", "english": "bright, alive" },
{ "spanish": "lucha", "english": "wrestle,  struggle,  ﬁght" },
{ "spanish": "daño", "english": "damage,  injury,  harm" },
{ "spanish": "intento", "english": "try,  attempt" },
{ "spanish": "enfermo", "english": "sick,  ill" },
{ "spanish": "piso", "english": "story,  ﬂoor" },
{ "spanish": "gesto", "english": "gesture" },
{ "spanish": "derecho", "english": "straight,  right" },
{ "spanish": "actual", "english": "current" },
{ "spanish": "diciembre", "english": "December" },
{ "spanish": "economía", "english": "economics,  economy,  thriftiness" },
{ "spanish": "introducir", "english": "bring in,  to introduce" },
{ "spanish": "totalmente", "english": "completely,  totally" },
{ "spanish": "cuánto", "english": "how much?" },
{ "spanish": "posición", "english": "position" },
{ "spanish": "lejos", "english": "off],  far[away" },
{ "spanish": "leche", "english": "milk" },
{ "spanish": "conciencia", "english": "consciousness,  conscience" },
{ "spanish": "aplicar", "english": "to apply" },
{ "spanish": "bajar", "english": "let down,  to come down" },
{ "spanish": "consejo", "english": "counsel,  council,  advice" },
{ "spanish": "próximo", "english": "next" },
{ "spanish": "piedra", "english": "rock,  stone" },
{ "spanish": "médico", "english": "doctor" },
{ "spanish": "director", "english": "principal,  manager,  director" },
{ "spanish": "recuperar", "english": "recover,  to recuperate" },
{ "spanish": "principal", "english": "principal, main" },
{ "spanish": "cuento", "english": "tale,  story" },
{ "spanish": "mirada", "english": "look,  gaze" },
{ "spanish": "siete", "english": "seven" },
{ "spanish": "duro", "english": "hard" },
{ "spanish": "espíritu", "english": "ghost,  spirit" },
{ "spanish": "artículo", "english": "item,  product,  article" },
{ "spanish": "trasladar", "english": "transfer,  to move" },
{ "spanish": "hábito", "english": "habit" },
{ "spanish": "positivo", "english": "positive" },
{ "spanish": "expresión", "english": "expression" },
{ "spanish": "exponer", "english": "expose,  to expound" },
{ "spanish": "letra", "english": "lyrics,  handwriting,  letter" },
{ "spanish": "partida", "english": "departure,  match,  game" },
{ "spanish": "sencillo", "english": "easy,  plain,  simple" },
{ "spanish": "apenas", "english": "barely,  hardly" },
{ "spanish": "estilo", "english": "style" },
{ "spanish": "perfecto", "english": "perfect" },
{ "spanish": "vuelta", "english": "turn,  return" },
{ "spanish": "excepción", "english": "exception" },
{ "spanish": "control", "english": "control" },
{ "spanish": "esperanza", "english": "hope" },
{ "spanish": "superior", "english": "upper,  superior" },
{ "spanish": "habitación", "english": "bedroom,  room,  habitat" },
{ "spanish": "manejar", "english": "handle,  to drive" },
{ "spanish": "causa", "english": "cause" },
{ "spanish": "semejante", "english": "alike,  such,  similar" },
{ "spanish": "alrededor", "english": "round,  around,  about" },
{ "spanish": "profesor", "english": "teacher,  professor" },
{ "spanish": "siquiera", "english": "even[if]" },
{ "spanish": "acompañar", "english": "to accompany" },
{ "spanish": "labor", "english": "task,  work,  labor" },
{ "spanish": "trabajador", "english": "laborer,  worker" },
{ "spanish": "carácter", "english": "nature,  personality" },
{ "spanish": "cantar", "english": "to sing" },
{ "spanish": "operar", "english": "to operate" },
{ "spanish": "obstante", "english": "noobstante: nevertheless" },
{ "spanish": "joven", "english": "young" },
{ "spanish": "sexo", "english": "sex" },
{ "spanish": "documento", "english": "document" },
{ "spanish": "motivo", "english": "cause,  motive" },
{ "spanish": "construir", "english": "build,  to construct" },
{ "spanish": "opinión", "english": "view,  opinion" },
{ "spanish": "dominar", "english": "master,  to dominate" },
{ "spanish": "oscuro", "english": "obscure,  dark" },
{ "spanish": "acordar", "english": "remind,  to remember" },
{ "spanish": "cerrar", "english": "to close" },
{ "spanish": "cadena", "english": "chain" },
{ "spanish": "tras", "english": "behind,  after" },
{ "spanish": "repartir", "english": "distribute,  deliver,  to divide" },
{ "spanish": "fenómeno", "english": "phenomenon" },
{ "spanish": "proceso", "english": "procedure, process" },
{ "spanish": "desarrollo", "english": "development" },
{ "spanish": "contacto", "english": "contact" },
{ "spanish": "dudar", "english": "to[have]doubt" },
{ "spanish": "prestar", "english": "to lend" },
{ "spanish": "guardar", "english": "save,  to keep" },
{ "spanish": "llorar", "english": "to cry" },
{ "spanish": "margen", "english": "margin,  edge,  border,  brink" },
{ "spanish": "hallar", "english": "to ﬁnd[out]" },
{ "spanish": "dolor", "english": "sorrow,  ache,  pain" },
{ "spanish": "bomba", "english": "explosion,  bomb,  pump" },
{ "spanish": "impresión", "english": "printing,  impression" },
{ "spanish": "respuesta", "english": "reply, answer" },
{ "spanish": "culpa", "english": "fault,  blame" },
{ "spanish": "añadir", "english": "to add" },
{ "spanish": "argentino", "english": "Argentine" },
{ "spanish": "durar", "english": "to last" },
{ "spanish": "tirar", "english": "pull,  to throw" },
{ "spanish": "colegio", "english": "college, [high]school" },
{ "spanish": "invitar", "english": "to invite" },
{ "spanish": "marido", "english": "husband" },
{ "spanish": "diario", "english": "daily" },
{ "spanish": "tarea", "english": "job,  task" },
{ "spanish": "acceso", "english": "entry,  access" },
{ "spanish": "impedir", "english": "hinder,  to prevent" },
{ "spanish": "crisis", "english": "crisis" },
{ "spanish": "sala", "english": "hall,  room" },
{ "spanish": "actitud", "english": "attitude" },
{ "spanish": "raro", "english": "scarce,  rare,  strange" },
{ "spanish": "muerto", "english": "dead" },
{ "spanish": "suerte", "english": "fortune,  luck" },
{ "spanish": "religioso", "english": "religious" },
{ "spanish": "instalar", "english": "to install" },
{ "spanish": "serie", "english": "series" },
{ "spanish": "cubrir", "english": "to cover" },
{ "spanish": "cercano", "english": "near" },
{ "spanish": "argumento", "english": "plot,  argument" },
{ "spanish": "prueba", "english": "test,  trial,  proof" },
{ "spanish": "hundir", "english": "submerge,  to sink" },
{ "spanish": "éxito", "english": "success" },
{ "spanish": "absoluto", "english": "absolute" },
{ "spanish": "pleno", "english": "full,  complete" },
{ "spanish": "normal", "english": "regular,  usual,  normal" },
{ "spanish": "funcionar", "english": "function,  to work" },
{ "spanish": "señalar", "english": "signal,  to point[out]" },
{ "spanish": "cuarto", "english": "fourth" },
{ "spanish": "conocido", "english": "well-known,  known" },
{ "spanish": "mezclar", "english": "to mix" },
{ "spanish": "paz", "english": "peace" },
{ "spanish": "proyecto", "english": "plan,  project" },
{ "spanish": "caja", "english": "safe,  box,  bank" },
{ "spanish": "rápido", "english": "fast,  quick" },
{ "spanish": "honor", "english": "honesty,  honor" },
{ "spanish": "capital", "english": "money[m],  city[f],  capital" },
{ "spanish": "liberar", "english": "liberate,  to free" },
{ "spanish": "completar", "english": "to complete" },
{ "spanish": "interior", "english": "inside,  interior" },
{ "spanish": "ajeno", "english": "detached,  not belonging to" },
{ "spanish": "despedir", "english": "dismiss,  to say goodbye[to]" },
{ "spanish": "chico", "english": "boy" },
{ "spanish": "nacimiento", "english": "origin,  birth" },
{ "spanish": "seco", "english": "arid,  dry" },
{ "spanish": "apoyo", "english": "backing,  support" },
{ "spanish": "dividir", "english": "to divide" },
{ "spanish": "pesado", "english": "tiresome,  boring,  heavy" },
{ "spanish": "texto", "english": "text" },
{ "spanish": "reserva", "english": "reserve,  reservation" },
{ "spanish": "defender", "english": "protect,  to defend" },
{ "spanish": "pertenecer", "english": "to belong" },
{ "spanish": "formación", "english": "education,  formation" },
{ "spanish": "boca", "english": "opening,  entrance,  mouth" },
{ "spanish": "distancia", "english": "distance" },
{ "spanish": "azul", "english": "blue" },
{ "spanish": "opinar", "english": "be of the opinion,  to think" },
{ "spanish": "máquina", "english": "machine" },
{ "spanish": "título", "english": "heading,  title" },
{ "spanish": "habitual", "english": "habitual,  usual,  customary" },
{ "spanish": "negar", "english": "refuse,  to deny" },
{ "spanish": "llamada", "english": "knock,  call" },
{ "spanish": "ideal", "english": "goal,  ideal" },
{ "spanish": "suyo", "english": "yours[informal],  theirs,  hers,  his" },
{ "spanish": "directo", "english": "straight,  direct" },
{ "spanish": "método", "english": "method" },
{ "spanish": "preciso", "english": "necessary,  precise" },
{ "spanish": "debajo", "english": "below,  underneath" },
{ "spanish": "averiguar", "english": "ﬁnd out,  to investigate" },
{ "spanish": "presión", "english": "pressure" },
{ "spanish": "ignorar", "english": "to be unaware" },
{ "spanish": "automóvil", "english": "automobile" },
{ "spanish": "detrás", "english": "behind" },
{ "spanish": "contenido", "english": "content,  contents" },
{ "spanish": "hija", "english": "daughter" },
{ "spanish": "agosto", "english": "August" },
{ "spanish": "cobrar", "english": "to charge[money]" },
{ "spanish": "barco", "english": "ship,  boat" },
{ "spanish": "americano", "english": "American" },
{ "spanish": "vender", "english": "to sell" },
{ "spanish": "sesenta", "english": "sixty" },
{ "spanish": "animar", "english": "to cheer up" },
{ "spanish": "página", "english": "page" },
{ "spanish": "notar", "english": "to notice" },
{ "spanish": "árbol", "english": "tree" },
{ "spanish": "plan", "english": "plan" },
{ "spanish": "alcance", "english": "scope,  reach" },
{ "spanish": "regresar", "english": "to return[to a place]" },
{ "spanish": "mandar", "english": "order,  to send" },
{ "spanish": "moda", "english": "form,  fashion" },
{ "spanish": "satisfacer", "english": "to satisfy" },
{ "spanish": "curiosidad", "english": "quaintness,  curiosity" },
{ "spanish": "escuela", "english": "school" },
{ "spanish": "memoria", "english": "memory" },
{ "spanish": "espejo", "english": "reﬂection,  mirror" },
{ "spanish": "elemento", "english": "element" },
{ "spanish": "romper", "english": "to break" },
{ "spanish": "matar", "english": "to kill" },
{ "spanish": "cola", "english": "queue,  line,  tail" },
{ "spanish": "juventud", "english": "youth" },
{ "spanish": "trato", "english": "agreement,  manner,  treatment" },
{ "spanish": "coche", "english": "carriage,  car" },
{ "spanish": "veinte", "english": "twenty" },
{ "spanish": "acudir", "english": "frequent,  go to,  to attend" },
{ "spanish": "examinar", "english": "inspect,  to examine" },
{ "spanish": "frío", "english": "cold" },
{ "spanish": "tensión", "english": "stress,  tension,  strain" },
{ "spanish": "expresar", "english": "to express" },
{ "spanish": "generación", "english": "generation" },
{ "spanish": "terreno", "english": "terrain,  earth,  ground" },
{ "spanish": "seguro", "english": "secure,  sure,  safe" },
{ "spanish": "raza", "english": "lineage,  race" },
{ "spanish": "arrancar", "english": "uproot,  to start[machine]" },
{ "spanish": "sexual", "english": "sexual" },
{ "spanish": "puesto", "english": "position,  place,  job" },
{ "spanish": "familiar", "english": "of the family,  familiar" },
{ "spanish": "aprobar", "english": "approve,  to pass[test]" },
{ "spanish": "abajo", "english": "downward,  below,  down" },
{ "spanish": "quejar", "english": "to complain" },
{ "spanish": "juicio", "english": "judgment" },
{ "spanish": "técnico", "english": "technical" },
{ "spanish": "jardín", "english": "garden" },
{ "spanish": "intervenir", "english": "to intervene" },
{ "spanish": "público", "english": "audience,  public" },
{ "spanish": "ritmo", "english": "rhythm" },
{ "spanish": "feliz", "english": "fortunate,  happy" },
{ "spanish": "exacto", "english": "true,  faithful,  exact" },
{ "spanish": "esposa", "english": "wife" },
{ "spanish": "personaje", "english": "character[e.g. movie]" },
{ "spanish": "patria", "english": "fatherland,  native land" },
{ "spanish": "calidad", "english": "quality" },
{ "spanish": "belleza", "english": "beauty" },
{ "spanish": "continuo", "english": "continuous" },
{ "spanish": "huella", "english": "track,  trace,  footstep" },
{ "spanish": "mezcla", "english": "blend,  mixture" },
{ "spanish": "ciego", "english": "blind" },
{ "spanish": "lejano", "english": "distant" },
{ "spanish": "gusto", "english": "preference,  taste,  pleasure" },
{ "spanish": "ejercicio", "english": "practice,  exercise" },
{ "spanish": "hospital", "english": "hospital" },
{ "spanish": "radio", "english": "communication[f],  set[m],  radio" },
{ "spanish": "treinta", "english": "thirty" },
{ "spanish": "salida", "english": "outcome,  escape,  exit" },
{ "spanish": "salvar", "english": "rescue,  to save" },
{ "spanish": "mar", "english": "sea" },
{ "spanish": "cuarto", "english": "chamber,  room" },
{ "spanish": "parar", "english": "to stop[moving]" },
{ "spanish": "saber", "english": "knowledge" },
{ "spanish": "cargo", "english": "fee,  charge,  position" },
{ "spanish": "poesía", "english": "poem,  poetry" },
{ "spanish": "música", "english": "music" },
{ "spanish": "estación", "english": "season,  station" },
{ "spanish": "justicia", "english": "fairness,  justice" },
{ "spanish": "brillante", "english": "sparkling,  shiny,  brilliant" },
{ "spanish": "destino", "english": "destiny,  destination" },
{ "spanish": "revolución", "english": "revolution" },
{ "spanish": "entrega", "english": "delivery" },
{ "spanish": "sensación", "english": "feeling,  sensation" },
{ "spanish": "agudo", "english": "acute,  sharp" },
{ "spanish": "rato", "english": "while,  moment,  time" },
{ "spanish": "doce", "english": "twelve" },
{ "spanish": "salto", "english": "hop,  jump,  skip" },
{ "spanish": "alegría", "english": "happiness,  joy" },
{ "spanish": "aun", "english": "still,  even[though]" },
{ "spanish": "operación", "english": "operation" },
{ "spanish": "delicado", "english": "delicate" },
{ "spanish": "nota", "english": "grade,  note" },
{ "spanish": "convencido", "english": "persuaded,  convinced" },
{ "spanish": "simple", "english": "simple-minded,  mere,  simple" },
{ "spanish": "secretario", "english": "secretary" },
{ "spanish": "exposición", "english": "display,  exhibition" },
{ "spanish": "clave", "english": "key" },
{ "spanish": "cruzar", "english": "to cross" },
{ "spanish": "personal", "english": "personal" },
{ "spanish": "pared", "english": "[interior]wall" },
{ "spanish": "griego", "english": "Greek" },
{ "spanish": "poderoso", "english": "powerful" },
{ "spanish": "punta", "english": "point,  tip" },
{ "spanish": "mundial", "english": "worldwide" },
{ "spanish": "empleo", "english": "job,  work,  occupation" }
];
